// <auto-generated />
namespace Miubuy.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class _020201 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_020201));
        
        string IMigrationMetadata.Id
        {
            get { return "202102020708258_020201"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
